// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.
#include <iostream>

using namespace std;

int main()
{
  int sum = 0;
  int MAX_SIZE = 50; 
  int fib [MAX_SIZE];//makes a static array of arbitrary size 50

  fib[0] = 1; fib[1] = 1;

  for (int n = 0; n < MAX_SIZE-1; n++){
    fib[n+2] = fib[n] + fib[n+1];//adds two numbers to get the next in the sequence
    if (fib[n] % 2==0 and fib[n] < 4000000){//if even and < 4mil
      sum += fib[n];
    }
  }
  cout <<sum<<endl;//print sum
}

//output is 4613732